### ISSUE TITLE
OpenSource project ?

### ISSUE THREAD

**Issue by timotheeguerinrb** [jsappme/BitcoinVsAltcoins#1]
Hello,
First thanks you for your work ! The NBTHub will be open source ?
It will be amazing to be able to contribute on it or maybe having a more open API to make a more powerfull dashboard and graph.

Thanks

**Comment by jsappme** [comment]
hello @timotheeguerinrb I don't plan to open source the code of the NBTHub for now. 

Feel free to access the open API of the NBT Hub in order to build your own dashboard. Let me know if you need more endpoints.

**Comment by jshield** [comment]
@jsappme have you published an OpenAPI spec somewhere?

**Comment by jsappme** [comment]
You can find more info at
https://github.com/jsappme/node-binance-trader#web-socket-api-specifications-

We are still working on a better documentation of our API.
