### ISSUE TITLE
Closed Orders Disappearing

### ISSUE THREAD

**Issue by erichstrange** [jsappme/BitcoinVsAltcoins#2]
There is an issue where closed orders are disappearing from view from https://bitcoinvsaltcoins.com/trader.

Have had this experience twice - both times it happens when the closed order has resulted in a negative PnL.

Overall PnL as displayed on page is still correct, however, because of the disappearing closed orders, if you were to manually add together all PnL's, it would appear as incorrect.

**Comment by jsappme** [comment]
Thanks @dargmuesli for the suggestion. I moved it. I will close it for now until we know more about this issue. The new site version will definitely fix all those ui issues.
